name: Build

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
    pull_request:
    release:
        types: [published]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        name: ${{ matrix.os }} Build
        # The type of runner that the job will run on
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        # Clones the repository
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Setup Cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: vex-desktop-deps

            - name: Install Dependencies
              run: yarn --network-concurrency 1
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.CI_KEY }}

            # Build
            - name: Build
              run: |
                  if [ "$RUNNER_OS" == "macOS" ]; then
                      ( yarn package-all )
                  else
                      ( yarn package )
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/upload-artifact@v2
              if: matrix.os == 'macOS-latest'
              with:
                  path: |
                      release/*.exe
                      release/*.dmg
                      release/*.deb
                      release/*.AppImage
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload release
              if: matrix.os == 'macOS-latest'
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: release/*.{exe,dmg,deb,AppImage}
                  tag: ${{ github.ref }}
                  overwrite: true
                  file_glob: true
