name: nightly
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:


jobs:
  nightly:
    name: nightly
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v2

        - name: Install Dependencies
          run: yarn --network-concurrency 1
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.CI_KEY }}

        # Build
        - name: Build
          run: |
            yarn package
            ls ./release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: release/*.{exe,dmg,deb,AppImage,txt}
            tag: nightly
            overwrite: true
            file_glob: true
