name: nightly
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:


jobs:
  nightly:
    name: nightly
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: dev-drprasad/delete-tag-and-release@v0.1.2
          with:
            delete_release: true # default: false
            tag_name: nightly # tag name to delete
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create a Release
          uses: actions/create-release@v1
          with:
            tag_name: nightly
            release_name: nightly
            token: ${{ secrets.GITHUB_TOKEN }}
